# Generated by Django 5.2.8

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LLMProviderConfig',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Configuration name', max_length=64, unique=True)),
                ('provider_type', models.CharField(choices=[('openai', 'OpenAI'), ('ollama', 'Ollama'), ('custom', 'Custom')], help_text='LLM provider type', max_length=32)),
                ('api_base', models.CharField(blank=True, default='', help_text='API base URL', max_length=512)),
                ('api_key_encrypted', models.CharField(blank=True, default='', help_text='Encrypted API key', max_length=512)),
                ('model_name', models.CharField(help_text='Model name to use', max_length=128)),
                ('config_json', models.JSONField(blank=True, default=dict, help_text='Additional configuration (temperature, max_tokens, etc.)')),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is the default provider')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this provider is active')),
                ('gmt_create', models.DateTimeField(auto_now_add=True)),
                ('gmt_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'LLM Provider Config',
                'verbose_name_plural': 'LLM Provider Configs',
                'db_table': 'chatbot_llm_provider',
            },
        ),
        migrations.CreateModel(
            name='RAGProviderConfig',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Configuration name', max_length=64, unique=True)),
                ('provider_type', models.CharField(choices=[('http', 'HTTP Service'), ('custom', 'Custom')], default='http', help_text='RAG provider type', max_length=32)),
                ('api_base', models.CharField(blank=True, default='', help_text='API base URL', max_length=512)),
                ('api_key_encrypted', models.CharField(blank=True, default='', help_text='Encrypted API key', max_length=512)),
                ('config_json', models.JSONField(blank=True, default=dict, help_text='Additional configuration')),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is the default provider')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this provider is active')),
                ('gmt_create', models.DateTimeField(auto_now_add=True)),
                ('gmt_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'RAG Provider Config',
                'verbose_name_plural': 'RAG Provider Configs',
                'db_table': 'chatbot_rag_provider',
            },
        ),
        migrations.CreateModel(
            name='ToolConfig',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Tool/Skill name', max_length=64, unique=True)),
                ('tool_type', models.CharField(choices=[('tool', 'Tool'), ('skill', 'Skill')], default='tool', help_text='Tool or Skill', max_length=32)),
                ('description', models.TextField(blank=True, default='', help_text='Tool description for LLM')),
                ('parameters_schema', models.JSONField(blank=True, default=dict, help_text='JSON Schema for tool parameters')),
                ('config_json', models.JSONField(blank=True, default=dict, help_text='Additional configuration')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this tool is active')),
                ('gmt_create', models.DateTimeField(auto_now_add=True)),
                ('gmt_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tool Config',
                'verbose_name_plural': 'Tool Configs',
                'db_table': 'chatbot_tool_config',
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('session_id', models.CharField(default=uuid.uuid4, help_text='Unique session identifier', max_length=64, unique=True)),
                ('user_id', models.CharField(db_index=True, help_text='User identifier', max_length=128)),
                ('title', models.CharField(blank=True, default='', help_text='Session title', max_length=256)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', help_text='Session status', max_length=16)),
                ('llm_provider_id', models.BigIntegerField(blank=True, db_index=True, help_text='LLM provider configuration ID', null=True)),
                ('agent_type', models.CharField(choices=[('react', 'ReAct Agent'), ('simple', 'Simple Agent')], default='react', help_text='Agent type for this session', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional session metadata')),
                ('gmt_create', models.DateTimeField(auto_now_add=True)),
                ('gmt_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chat Session',
                'verbose_name_plural': 'Chat Sessions',
                'db_table': 'chatbot_session',
                'ordering': ['-gmt_create'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('message_id', models.CharField(default=uuid.uuid4, help_text='Unique message identifier', max_length=64, unique=True)),
                ('session_id', models.CharField(db_index=True, help_text='Associated chat session ID', max_length=64)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System'), ('tool', 'Tool')], help_text='Message sender role', max_length=16)),
                ('content', models.TextField(help_text='Message content')),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('thought', 'Thought'), ('action', 'Action'), ('observation', 'Observation')], default='text', help_text='Type of message', max_length=16)),
                ('parent_message_id', models.CharField(blank=True, db_index=True, help_text='Parent message ID for multi-answer scenarios', max_length=64, null=True)),
                ('group_id', models.CharField(blank=True, db_index=True, help_text='Group ID for multi-question scenarios', max_length=64, null=True)),
                ('token_count', models.IntegerField(default=0, help_text='Token count for this message')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional message metadata')),
                ('gmt_create', models.DateTimeField(auto_now_add=True)),
                ('gmt_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'db_table': 'chatbot_message',
                'ordering': ['gmt_create'],
                'indexes': [models.Index(fields=['session_id', 'gmt_create'], name='chatbot_mes_session_2b763e_idx')],
            },
        ),
        migrations.CreateModel(
            name='SessionContext',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('session_id', models.CharField(help_text='Associated chat session ID', max_length=64, unique=True)),
                ('messages', models.JSONField(default=list, help_text='Complete LLM context messages (excluding system prompt)')),
                ('gmt_create', models.DateTimeField(auto_now_add=True)),
                ('gmt_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Session Context',
                'verbose_name_plural': 'Session Contexts',
                'db_table': 'chatbot_session_context',
            },
        ),
    ]
