# Generated by Django 4.1 on 2026-03-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.CharField(help_text='Unique tenant identifier', max_length=64, unique=True)),
                ('name', models.CharField(help_text='Human-readable tenant name', max_length=128)),
                ('token_hash', models.CharField(help_text='SHA-256 hash of the authentication token', max_length=128, unique=True)),
                ('config_json', models.JSONField(blank=True, default=dict, help_text='Tenant-specific configuration (overrides settings.CHATBOT)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this tenant is active')),
                ('gmt_create', models.DateTimeField(auto_now_add=True)),
                ('gmt_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'db_table': 'chatbot_tenant',
            },
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='tenant_id',
            field=models.CharField(db_index=True, default='default', help_text='Tenant identifier', max_length=64),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='tenant_id',
            field=models.CharField(db_index=True, default='default', help_text='Tenant identifier', max_length=64),
        ),
        migrations.AddField(
            model_name='llmproviderconfig',
            name='tenant_id',
            field=models.CharField(db_index=True, default='default', help_text='Tenant identifier', max_length=64),
        ),
        migrations.AddField(
            model_name='ragproviderconfig',
            name='tenant_id',
            field=models.CharField(db_index=True, default='default', help_text='Tenant identifier', max_length=64),
        ),
        migrations.AddField(
            model_name='sessioncontext',
            name='tenant_id',
            field=models.CharField(db_index=True, default='default', help_text='Tenant identifier', max_length=64),
        ),
        migrations.AddField(
            model_name='toolconfig',
            name='tenant_id',
            field=models.CharField(db_index=True, default='default', help_text='Tenant identifier', max_length=64),
        ),
        migrations.AlterField(
            model_name='llmproviderconfig',
            name='name',
            field=models.CharField(help_text='Configuration name', max_length=64),
        ),
        migrations.AlterField(
            model_name='ragproviderconfig',
            name='name',
            field=models.CharField(help_text='Configuration name', max_length=64),
        ),
        migrations.AlterField(
            model_name='toolconfig',
            name='name',
            field=models.CharField(help_text='Tool/Skill name', max_length=64),
        ),
        migrations.AddConstraint(
            model_name='llmproviderconfig',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'name'), name='uk_llm_tenant_name'),
        ),
        migrations.AddConstraint(
            model_name='ragproviderconfig',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'name'), name='uk_rag_tenant_name'),
        ),
        migrations.AddConstraint(
            model_name='toolconfig',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'name'), name='uk_tool_tenant_name'),
        ),
    ]
