# Generated by Django 4.1 on 2026-03-10 11:41

import apps.entities.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_add_tenant_and_tenant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='metadata',
            field=apps.entities.fields.JsonTextField(blank=True, default=dict, help_text='Additional message metadata'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='metadata',
            field=apps.entities.fields.JsonTextField(blank=True, default=dict, help_text='Additional session metadata'),
        ),
        migrations.AlterField(
            model_name='llmproviderconfig',
            name='config_json',
            field=apps.entities.fields.JsonTextField(blank=True, default=dict, help_text='Additional configuration (temperature, max_tokens, etc.)'),
        ),
        migrations.AlterField(
            model_name='ragproviderconfig',
            name='config_json',
            field=apps.entities.fields.JsonTextField(blank=True, default=dict, help_text='Additional configuration'),
        ),
        migrations.AlterField(
            model_name='sessioncontext',
            name='messages',
            field=apps.entities.fields.JsonTextField(blank=True, default=list, help_text='Complete LLM context messages (excluding system prompt)'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='config_json',
            field=apps.entities.fields.JsonTextField(blank=True, default=dict, help_text='Tenant-specific configuration (overrides settings.CHATBOT)'),
        ),
        migrations.AlterField(
            model_name='toolconfig',
            name='config_json',
            field=apps.entities.fields.JsonTextField(blank=True, default=dict, help_text='Additional configuration'),
        ),
        migrations.AlterField(
            model_name='toolconfig',
            name='parameters_schema',
            field=apps.entities.fields.JsonTextField(blank=True, default=dict, help_text='JSON Schema for tool parameters'),
        ),
    ]
