# Generated by Django 4.1.2 on 2026-03-23 16:41

import apps.entities.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_json_to_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.CharField(db_index=True, default='default', help_text='Tenant identifier', max_length=64)),
                ('skill_id', models.CharField(default=uuid.uuid4, help_text='Unique skill identifier', max_length=64, unique=True)),
                ('name', models.CharField(help_text='Skill name', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Skill description')),
                ('content', models.TextField(help_text='SKILL.md format content')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether the skill is active')),
                ('metadata', apps.entities.fields.JsonTextField(blank=True, default=dict, help_text='Additional skill metadata')),
                ('gmt_create', models.DateTimeField(auto_now_add=True)),
                ('gmt_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'db_table': 'chatbot_skill',
                'ordering': ['-gmt_create'],
                'unique_together': {('tenant_id', 'name')},
            },
        ),
    ]
