# Generated by Django 4.1.12 on 2026-03-26 10:20

import apps.entities.skill
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_add_skill_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='McpServerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('command', models.CharField(max_length=500)),
                ('args', models.JSONField(default=list, help_text='Command arguments as JSON array')),
                ('env', models.JSONField(blank=True, default=dict, help_text='Environment variables as JSON object')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('tools_cache', models.JSONField(blank=True, default=list, help_text='Cached list of tools from server')),
                ('tenant_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mcp_server_config',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='llmproviderconfig',
            name='provider_type',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('ollama', 'Ollama'), ('custom', 'Custom'), ('ucloud', 'UCloud'), ('cockpit', 'Cockpit'), ('asri_gateway', 'AsriGateway')], help_text='LLM provider type', max_length=32),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(help_text='Skill name (English letters, numbers, underscores, hyphens only)', max_length=255, validators=[apps.entities.skill.validate_skill_name]),
        ),
        migrations.CreateModel(
            name='McpToolMockConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_id', models.CharField(db_index=True, max_length=100)),
                ('tool_name', models.CharField(db_index=True, max_length=200)),
                ('enabled', models.BooleanField(default=False)),
                ('mode', models.CharField(choices=[('fixed', 'Fixed Input-Output Pairs'), ('random', 'Random Outputs'), ('manual', 'Manual Input-Output')], default='manual', max_length=20)),
                ('pairs', models.JSONField(blank=True, default=list)),
                ('random_outputs', models.JSONField(blank=True, default=list)),
                ('manual_input', models.JSONField(blank=True, default=dict)),
                ('manual_output', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mcp_tool_mock_config',
                'ordering': ['-created_at'],
                'unique_together': {('server_id', 'tool_name')},
            },
        ),
    ]
