# Generated by Django 4.1.2 on 2026-03-26 14:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_mcpserverconfig_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="对应 Prompt 类的注册名，如 'react', 'skill_decision'", max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='模板描述')),
                ('system_template', models.TextField(blank=True, help_text='System Prompt 模板（Jinja2），空白则使用硬编码')),
                ('user_template_mode', models.CharField(choices=[('generic', '通用模式 [system, *history, user]'), ('custom', '自定义模式（使用 user_template）')], default='generic', help_text='generic=通用模式，custom=自定义', max_length=20)),
                ('user_template', models.TextField(blank=True, help_text='用户消息模板（Jinja2），仅在 custom 模式下使用')),
                ('extractor_config', models.JSONField(blank=True, default=dict, help_text='\n        解析器配置，示例：\n        {\n            "type": "xml_tags",\n            "tool_keys": ["tool_call"],\n            "think_keys": ["think"],\n            "answer_keys": ["answer"]\n        }\n        type 可选值：xml_tags | json | react\n        ')),
                ('is_active', models.BooleanField(default=True, help_text='启用后覆盖硬编码')),
                ('priority', models.IntegerField(default=0, help_text='多模板时优先级')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'chatbot_prompt_template',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='prompttemplate',
            index=models.Index(fields=['name'], name='chatbot_pro_name_a3c5c6_idx'),
        ),
        migrations.AddIndex(
            model_name='prompttemplate',
            index=models.Index(fields=['is_active'], name='chatbot_pro_is_acti_c6ac3f_idx'),
        ),
    ]
