# Generated by Django 4.1.2 on 2026-03-26 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_prompttemplate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prompttemplate',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='prompttemplate',
            name='priority',
        ),
    ]
