# Generated by Django 4.1.2 on 2026-03-28 09:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_remove_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMemory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, max_length=64)),
                ('tenant_id', models.CharField(db_index=True, default='', max_length=64)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('preference', '偏好'), ('fact', '事实'), ('goal', '目标'), ('other', '其他')], default='other', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'chatbot_user_memory',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='usermemory',
            index=models.Index(fields=['user_id', 'tenant_id', '-created_at'], name='chatbot_use_user_id_72df52_idx'),
        ),
        migrations.AddIndex(
            model_name='usermemory',
            index=models.Index(fields=['user_id', 'tenant_id', 'category'], name='chatbot_use_user_id_8cac1a_idx'),
        ),
    ]
