# Generated by Django 4.1.12 on 2026-03-27 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0007_remove_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmproviderconfig",
            name="purpose",
            field=models.CharField(
                choices=[("chatbot", "Chatbot"), ("copilot", "Copilot")],
                default="chatbot",
                help_text="Model purpose (chatbot or copilot)",
                max_length=32,
            ),
        ),
    ]
