# Generated by Django 4.1.2 on 2026-03-31 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_add_purpose_to_llm_provider'),
        ('apps', '0008_add_user_memory'),
    ]

    operations = [
    ]
