# Generated by Django 4.1.2 on 2026-04-15 09:43

import apps.entities.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_simplify_mcp_config_to_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcpserverconfig',
            name='args',
            field=apps.entities.fields.JsonTextField(blank=True, default=list, help_text='Command arguments as JSON array'),
        ),
        migrations.AlterField(
            model_name='mcpserverconfig',
            name='config',
            field=apps.entities.fields.JsonTextField(blank=True, default=dict, help_text='Client-specific configuration'),
        ),
        migrations.AlterField(
            model_name='mcpserverconfig',
            name='env',
            field=apps.entities.fields.JsonTextField(blank=True, default=dict, help_text='Environment variables as JSON object'),
        ),
        migrations.AlterField(
            model_name='mcpserverconfig',
            name='tools_cache',
            field=apps.entities.fields.JsonTextField(blank=True, default=list, help_text='Cached list of tools from server'),
        ),
        migrations.AlterField(
            model_name='mcptoolmockconfig',
            name='manual_input',
            field=apps.entities.fields.JsonTextField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='mcptoolmockconfig',
            name='manual_output',
            field=apps.entities.fields.JsonTextField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='mcptoolmockconfig',
            name='pairs',
            field=apps.entities.fields.JsonTextField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='mcptoolmockconfig',
            name='random_outputs',
            field=apps.entities.fields.JsonTextField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='prompttemplate',
            name='extractor_config',
            field=apps.entities.fields.JsonTextField(blank=True, default=dict, help_text='\n        解析器配置，示例：\n        {\n            "type": "xml_tags",\n            "tool_keys": ["tool_call"],\n            "think_keys": ["think"],\n            "answer_keys": ["answer"]\n        }\n        type 可选值：xml_tags | json | react\n        '),
        ),
        migrations.AlterField(
            model_name='usermemory',
            name='metadata',
            field=apps.entities.fields.JsonTextField(blank=True, default=dict),
        ),
    ]
