# Generated by Django 5.2.8 on 2026-04-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_json_to_text_remaining'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mcpserverconfig',
            options={'ordering': ['-gmt_create']},
        ),
        migrations.AlterModelOptions(
            name='mcptoolmockconfig',
            options={'ordering': ['-gmt_create']},
        ),
        migrations.AlterModelOptions(
            name='prompttemplate',
            options={'ordering': ['-gmt_create']},
        ),
        migrations.AlterModelOptions(
            name='usermemory',
            options={'ordering': ['-gmt_create']},
        ),
        migrations.RemoveIndex(
            model_name='usermemory',
            name='chatbot_use_user_id_72df52_idx',
        ),
        migrations.RenameField(
            model_name='mcpserverconfig',
            old_name='created_at',
            new_name='gmt_create',
        ),
        migrations.RenameField(
            model_name='mcpserverconfig',
            old_name='updated_at',
            new_name='gmt_modified',
        ),
        migrations.RenameField(
            model_name='mcptoolmockconfig',
            old_name='created_at',
            new_name='gmt_create',
        ),
        migrations.RenameField(
            model_name='mcptoolmockconfig',
            old_name='updated_at',
            new_name='gmt_modified',
        ),
        migrations.RenameField(
            model_name='prompttemplate',
            old_name='created_at',
            new_name='gmt_create',
        ),
        migrations.RenameField(
            model_name='prompttemplate',
            old_name='updated_at',
            new_name='gmt_modified',
        ),
        migrations.RenameField(
            model_name='usermemory',
            old_name='created_at',
            new_name='gmt_create',
        ),
        migrations.RenameField(
            model_name='usermemory',
            old_name='updated_at',
            new_name='gmt_modified',
        ),
        migrations.AddIndex(
            model_name='usermemory',
            index=models.Index(fields=['user_id', 'tenant_id', '-gmt_create'], name='chatbot_use_user_id_f6ccd2_idx'),
        ),
    ]
