# Generated by Django 5.2.8 on 2026-04-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_alter_mcpserverconfig_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='external_session_id',
            field=models.CharField(
                max_length=128,
                null=True,
                blank=True,
                db_index=True,
                help_text='External system session ID for third-party integration',
            ),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['external_session_id'], name='chatbot_sess_external_session_id_idx'),
        ),
    ]
