# Generated by Django 5.2.8 on 2026-04-28 03:46

import apps.entities.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0015_add_version_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='HookConfig',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.CharField(db_index=True, default='default', help_text='租户 ID', max_length=64)),
                ('hook_type', models.CharField(help_text='Hook 类型标识，如 tool_confirmation', max_length=64)),
                ('hook_name', models.CharField(help_text='Hook 实例名称，同一 tenant 下唯一', max_length=128)),
                ('description', models.TextField(blank=True, default='', help_text='Hook 描述')),
                ('is_active', models.BooleanField(default=True, help_text='是否启用')),
                ('config_json', apps.entities.fields.JsonTextField(blank=True, default=dict, help_text='Hook 自定义参数，如 {"timeout": 30, "tools": ["send_email"]}')),
                ('gmt_create', models.DateTimeField(auto_now_add=True)),
                ('gmt_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'chatbot_hook_config',
                'ordering': ['-gmt_create'],
            },
        ),
        migrations.RemoveIndex(
            model_name='chatsession',
            name='chatbot_sess_external_session_id_idx',
        ),
        migrations.RemoveIndex(
            model_name='chatsession',
            name='chatbot_sess_source_external_idx',
        ),
        migrations.AlterField(
            model_name='llmproviderconfig',
            name='provider_type',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('ollama', 'Ollama'), ('ucloud', 'UCloud'), ('cockpit', 'Cockpit'), ('asri_gateway', 'AsriGateway')], help_text='LLM provider type', max_length=32),
        ),
        migrations.AddConstraint(
            model_name='hookconfig',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'hook_name'), name='uk_hook_tenant_name'),
        ),
    ]
