# Generated by Django 4.1.2 on 2026-05-13 08:56

import apps.entities.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0016_hookconfig_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenUsage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.CharField(db_index=True, default='default', help_text='Tenant identifier', max_length=64)),
                ('session_id', models.CharField(db_index=True, help_text='Associated chat session ID', max_length=64)),
                ('user_id', models.CharField(blank=True, db_index=True, default='', help_text='User identifier', max_length=128)),
                ('llm_provider', models.CharField(blank=True, db_index=True, default='', help_text='LLM provider name (e.g., openai, ucloud)', max_length=64)),
                ('model_name', models.CharField(blank=True, default='', help_text='LLM model name (e.g., gpt-4, qwen3-32b)', max_length=128)),
                ('prompt_tokens', models.IntegerField(default=0, help_text='Number of prompt tokens')),
                ('completion_tokens', models.IntegerField(default=0, help_text='Number of completion tokens')),
                ('cached_tokens', models.IntegerField(default=0, help_text='Number of cached (KV cache hit) tokens')),
                ('total_tokens', models.IntegerField(default=0, help_text='Total tokens (prompt + completion, excluding cached)')),
                ('cache_hit_rate', models.FloatField(default=0.0, help_text='Cache hit rate as a decimal (0.0 ~ 1.0)')),
                ('duration_ms', models.FloatField(default=0.0, help_text='LLM call duration in milliseconds')),
                ('finish_reason', models.CharField(blank=True, default='', help_text='Reason for completion (stop, length, etc.)', max_length=32)),
                ('metadata', apps.entities.fields.JsonTextField(blank=True, default=dict, help_text='Additional metadata for this LLM call')),
                ('gmt_create', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation time')),
            ],
            options={
                'verbose_name': 'Token Usage Record',
                'verbose_name_plural': 'Token Usage Records',
                'db_table': 'chatbot_token_usage',
                'ordering': ['-gmt_create'],
            },
        ),
        migrations.AddIndex(
            model_name='tokenusage',
            index=models.Index(fields=['tenant_id', 'gmt_create'], name='chatbot_tok_tenant__ba632b_idx'),
        ),
        migrations.AddIndex(
            model_name='tokenusage',
            index=models.Index(fields=['session_id', 'gmt_create'], name='chatbot_tok_session_07f60a_idx'),
        ),
        migrations.AddIndex(
            model_name='tokenusage',
            index=models.Index(fields=['model_name', 'gmt_create'], name='chatbot_tok_model_n_8be039_idx'),
        ),
    ]
