# Generated by Django 4.1.2 on 2026-05-14 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0017_tokenusage_tokenusage_chatbot_tok_tenant__ba632b_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenusage',
            name='chunk_count',
            field=models.IntegerField(default=0, help_text='Number of content chunks received'),
        ),
        migrations.AddField(
            model_name='tokenusage',
            name='tpot_ms',
            field=models.FloatField(default=0.0, help_text='Average time per output token in milliseconds'),
        ),
        migrations.AddField(
            model_name='tokenusage',
            name='ttft_ms',
            field=models.FloatField(default=0.0, help_text='Time to first token in milliseconds'),
        ),
    ]
