# Generated by Django 4.1.2 on 2026-05-21 11:31

import apps.entities.fields
from django.db import migrations


class Migration(migrations.Migration):

    # This migration replaces the old PromptLayer chain:
    #   0019_promptlayer_model → create PromptLayer table
    #   0020_migrate_templates_to_layers → data migration
    #   0021_prompt_layer_redesign → schema redesign
    #   0022_remove_system_core_rules_layers → cleanup
    # The net effect is the same: PromptTemplate gets a `layers` field.
    replaces = [
        ('apps', '0019_promptlayer_model'),
        ('apps', '0020_migrate_templates_to_layers'),
        ('apps', '0021_prompt_layer_redesign'),
        ('apps', '0022_remove_system_core_rules_layers'),
    ]

    dependencies = [
        ('apps', '0018_tokenusage_chunk_count_tokenusage_tpot_ms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompttemplate',
            name='layers',
            field=apps.entities.fields.JsonTextField(blank=True, default=list, help_text='Prompt layers 配置（JSON 数组）。\n        第一条 target=system 的 layer 相当于旧版的 system_template。\n        每项包含：name(str), target(system|user), strategy(always|first_turn),\n        template(str, Jinja2), order(int), is_active(bool)。\n        当 layers 非空时优先于 system_template。'),
        ),
    ]
