# Generated by Django 4.1.12 on 2026-05-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0019_prompttemplate_layers'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenusage',
            name='gmt_modified',
            field=models.DateTimeField(auto_now=True, help_text='Record modification time'),
        ),
    ]
