# Generated by Django 4.1.12 on 2026-05-21 11:53

import apps.entities.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0020_tokenusage_gmt_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenusage',
            name='cache_hit_rate',
            field=apps.entities.fields.FloatCharField(blank=True, default=0.0, help_text='Cache hit rate as a decimal (0.0 ~ 1.0)', max_length=32),
        ),
        migrations.AlterField(
            model_name='tokenusage',
            name='duration_ms',
            field=apps.entities.fields.FloatCharField(blank=True, default=0.0, help_text='LLM call duration in milliseconds', max_length=32),
        ),
        migrations.AlterField(
            model_name='tokenusage',
            name='tpot_ms',
            field=apps.entities.fields.FloatCharField(blank=True, default=0.0, help_text='Average time per output token in milliseconds', max_length=32),
        ),
        migrations.AlterField(
            model_name='tokenusage',
            name='ttft_ms',
            field=apps.entities.fields.FloatCharField(blank=True, default=0.0, help_text='Time to first token in milliseconds', max_length=32),
        ),
    ]
