# Generated by Django 4.1.2 on 2026-05-24 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0021_alter_tokenusage_cache_hit_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompttemplate',
            name='tenant_id',
            field=models.CharField(db_index=True, default='example', help_text='租户标识', max_length=64),
        ),
        migrations.AlterField(
            model_name='prompttemplate',
            name='name',
            field=models.CharField(help_text="对应 Prompt 类的注册名，如 'react', 'skill_decision'", max_length=100),
        ),
        migrations.AddConstraint(
            model_name='prompttemplate',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'name'), name='uk_prompt_template_tenant_id_name'),
        ),
    ]
