# Generated by Django 4.1.2 on 2026-05-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0024_mcptoolmockconfig_tenant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcptoolmockconfig',
            name='tenant_id',
            field=models.CharField(db_index=True, default='example', help_text='Tenant identifier', max_length=100),
        ),
    ]
