# Generated by Django 4.1.2 on 2026-05-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0025_alter_mcptoolmockconfig_tenant_id'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveConstraint(
                    model_name='prompttemplate',
                    name='uk_prompt_template_tenant_id_name',
                ),
                migrations.AddConstraint(
                    model_name='prompttemplate',
                    constraint=models.UniqueConstraint(fields=('tenant_id', 'name'), name='uk_prompt_tenant_id_name'),
                ),
                migrations.AlterModelTable(
                    name='prompttemplate',
                    table='chatbot_prompt',
                ),
            ],
        ),
    ]
