# Generated by Django 4.1.2 on 2026-06-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0027_merge_20260604'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RenameIndex(
                    model_name='prompttemplate',
                    new_name='chatbot_pro_name_83f4d7_idx',
                    old_name='chatbot_pro_name_a3c5c6_idx',
                ),
                migrations.RenameIndex(
                    model_name='prompttemplate',
                    new_name='chatbot_pro_is_acti_d68786_idx',
                    old_name='chatbot_pro_is_acti_c6ac3f_idx',
                ),
            ],
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='agent_type',
            field=models.CharField(choices=[('react', 'ChatAgent'), ('simple', 'Simple Agent')], default='react', help_text='Agent type for this session', max_length=32),
        ),
        migrations.AlterField(
            model_name='llmproviderconfig',
            name='provider_type',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('ollama', 'Ollama'), ('ucloud', 'UCloud'), ('asri_gateway', 'AsriGateway')], help_text='LLM provider type', max_length=32),
        ),
    ]
