# Generated by Django 4.1.12 on 2026-06-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0029_create_chatbot_prompt_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmproviderconfig',
            name='provider_type',
            field=models.CharField(help_text='LLM provider type (validated by Registry at runtime)', max_length=32),
        ),
    ]
