# Generated by Django 4.1.2 on 2026-06-04 21:34

import apps.entities.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0030_alter_llmproviderconfig_provider_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.CharField(default='example', help_text='租户标识', max_length=64)),
                ('name', models.CharField(help_text='快照名称', max_length=128)),
                ('description', models.TextField(blank=True, default='', help_text='快照描述')),
                ('source_session_id', models.CharField(blank=True, help_text='来源会话 ID，null 表示手动创建', max_length=64, null=True)),
                ('snapshot_data', apps.entities.fields.JsonTextField(blank=True, default=dict, help_text='复合配置快照，JSON 格式')),
                ('tags', apps.entities.fields.JsonTextField(blank=True, default=list, help_text='标签，用于分类/筛选')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='是否可用')),
                ('created_by', models.CharField(blank=True, default='', help_text='创建者标识', max_length=64)),
                ('gmt_create', models.DateTimeField(auto_now_add=True)),
                ('gmt_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'chatbot_session_snapshot',
                'ordering': ['-gmt_create'],
            },
        ),
        migrations.AddIndex(
            model_name='sessionsnapshot',
            index=models.Index(fields=['tenant_id', 'gmt_create'], name='idx_ss_tenant_created'),
        ),
        migrations.AddIndex(
            model_name='sessionsnapshot',
            index=models.Index(fields=['tenant_id', 'is_active'], name='idx_ss_tenant_active'),
        ),
    ]
