# Generated by Django 4.1.12 on 2026-06-15 14:40

import apps.entities.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0031_create_session_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompttemplate',
            name='description',
            field=models.TextField(blank=True, help_text='Template description'),
        ),
        migrations.AlterField(
            model_name='prompttemplate',
            name='extractor_config',
            field=apps.entities.fields.JsonTextField(blank=True, default=dict, help_text='\n        Parser configuration, example:\n        {\n            "type": "xml_tags",\n            "tool_keys": ["tool_call"],\n            "think_keys": ["think"],\n            "answer_keys": ["answer"]\n        }\n        type options: xml_tags | json | react\n        '),
        ),
        migrations.AlterField(
            model_name='prompttemplate',
            name='is_active',
            field=models.BooleanField(default=True, help_text='When enabled, overrides hardcoded defaults'),
        ),
        migrations.AlterField(
            model_name='prompttemplate',
            name='layers',
            field=apps.entities.fields.JsonTextField(blank=True, default=list, help_text='Prompt layers configuration (JSON array).\n        The first layer with target=system is equivalent to the old system_template.\n        Each item contains: name(str), target(system|user), strategy(always|first_turn),\n        template(str, Jinja2), order(int), is_active(bool).\n        When layers is non-empty, it takes priority over system_template.'),
        ),
        migrations.AlterField(
            model_name='prompttemplate',
            name='name',
            field=models.CharField(help_text="Corresponds to the Prompt class registration name, e.g. 'react', 'skill_decision'", max_length=100),
        ),
        migrations.AlterField(
            model_name='prompttemplate',
            name='system_template',
            field=models.TextField(blank=True, help_text='System Prompt template (Jinja2), empty uses hardcoded default'),
        ),
        migrations.AlterField(
            model_name='prompttemplate',
            name='tenant_id',
            field=models.CharField(db_index=True, default='example', help_text='Tenant identifier', max_length=64),
        ),
        migrations.AlterField(
            model_name='prompttemplate',
            name='user_template',
            field=models.TextField(blank=True, help_text='User message template (Jinja2), only used in custom mode'),
        ),
        migrations.AlterField(
            model_name='prompttemplate',
            name='user_template_mode',
            field=models.CharField(choices=[('generic', 'Generic mode [system, *history, user]'), ('custom', 'Custom mode (use user_template)')], default='generic', help_text='generic=generic mode, custom=custom mode', max_length=20),
        ),
        migrations.AlterField(
            model_name='usermemory',
            name='category',
            field=models.CharField(choices=[('preference', 'Preference'), ('fact', 'Fact'), ('goal', 'Goal'), ('other', 'Other')], default='other', max_length=32),
        ),
        migrations.AlterField(
            model_name='versionsnapshot',
            name='created_by',
            field=models.CharField(blank=True, default='', help_text='Creator identifier', max_length=64),
        ),
        migrations.AlterField(
            model_name='versionsnapshot',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Version change description'),
        ),
        migrations.AlterField(
            model_name='versionsnapshot',
            name='entity_id',
            field=models.CharField(db_index=True, help_text='ID of the associated entity (PromptTemplate.id or Skill.skill_id)', max_length=64),
        ),
        migrations.AlterField(
            model_name='versionsnapshot',
            name='entity_type',
            field=models.CharField(choices=[('prompt_template', 'Prompt Template'), ('skill', 'Skill')], db_index=True, help_text='Entity type: prompt_template or skill', max_length=32),
        ),
        migrations.AlterField(
            model_name='versionsnapshot',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this is the currently active version'),
        ),
        migrations.AlterField(
            model_name='versionsnapshot',
            name='label',
            field=models.CharField(blank=True, default='', help_text="User-defined version label, e.g. 'v1.0-prod'", max_length=128),
        ),
        migrations.AlterField(
            model_name='versionsnapshot',
            name='snapshot_data',
            field=apps.entities.fields.JsonTextField(blank=True, default=dict, help_text='Complete entity snapshot in JSON format'),
        ),
        migrations.AlterField(
            model_name='versionsnapshot',
            name='tenant_id',
            field=models.CharField(default='example', help_text='Tenant identifier', max_length=64),
        ),
        migrations.AlterField(
            model_name='versionsnapshot',
            name='version_number',
            field=models.PositiveIntegerField(help_text='Version number, auto-incremented within the same entity'),
        ),
    ]
