"""
JSON content extractor
"""
import json
import re
from typing import List, Tuple, Optional

from .extractor import BaseContentExtractor
from .base import LLMRes, LLMResChunk


class JSONExtractor(BaseContentExtractor):
    """JSON extractor

    Parses {"key": "value"} format, supports streaming and non-streaming extraction.
    Includes preprocessing logic to fix common JSON formatting issues (e.g., markdown code block, Chinese quotes, etc.).
    """

    def __init__(self, default_type: str = "think"):
        super().__init__(default_type)
        # Streaming state
        self._buffer = ""
        self._current_key_index: int | None = None  # current key index being output
        self._last_parse_success = False  # whether last parse succeeded

    def _preprocess(self, text: str) -> str:
        """Preprocess JSON text, fix common formatting issues

        1. Remove markdown code block markers
        2. Fix Chinese quote issues in JSON strings
        """
        # Remove markdown code block markers
        text = re.sub(r'^```json\s*', '', text, flags=re.IGNORECASE | re.MULTILINE)
        text = re.sub(r'^```\s*$', '', text, flags=re.MULTILINE)

        # If content starts with ``` but end not matched, try to match
        # Keep content after ```json
        if '```' in text:
            # Find the first ```json or ``` position and keep content after it
            match = re.search(r'```json\s*', text, re.IGNORECASE)
            if match:
                text = text[match.end():]
            else:
                match = re.search(r'```\s*', text)
                if match:
                    text = text[match.end():]

        return text

    def _fix_json_quotes(self, json_str: str) -> str:
        """Attempt to fix quote issues in JSON

        Common issue: LLM uses Chinese quotes "..." or "..." inside JSON string values
        These quotes break JSON parsing.
        """
        result = []
        i = 0
        in_string = False
        escape_next = False

        while i < len(json_str):
            char = json_str[i]

            if escape_next:
                result.append(char)
                escape_next = False
                i += 1
                continue

            if char == '\\':
                result.append(char)
                escape_next = True
                i += 1
                continue

            if char == '"':
                if not in_string:
                    # JSON string start
                    in_string = True
                    result.append(char)
                else:
                    # JSON string end
                    in_string = False
                    result.append(char)
            elif in_string:
                # Inside string, keep all characters (including Chinese quotes)
                result.append(char)
            else:
                # Outside string
                result.append(char)

            i += 1

        return ''.join(result)

    def _try_parse_json(self, text: str) -> Optional[dict]:
        """Attempt to parse JSON, fall back to regex extraction on failure

        Returns:
            Returns dict on success, None on failure
        """
        # Preprocess: remove markdown
        preprocessed = self._preprocess(text)

        # First attempt: direct parse
        try:
            return json.loads(preprocessed)
        except json.JSONDecodeError:
            pass

        # Second attempt: retry after stripping whitespace
        try:
            return json.loads(preprocessed.strip())
        except json.JSONDecodeError:
            pass

        # Third attempt: use regex extraction
        return self._extract_by_regex(preprocessed)

    def _extract_by_regex(self, text: str) -> Optional[dict]:
        """Use state machine to extract JSON key-value (when standard parsing fails)

        Handles imperfect JSON generated by LLM (e.g., unescaped quotes inside strings)
        Key: distinguish JSON syntax double quotes from ordinary quotes
        """
        result = {}

        # Find JSON object boundaries
        start = text.find('{')
        end = text.rfind('}')
        if start == -1 or end == -1 or start >= end:
            return None

        json_content = text[start:end + 1]

        def look_ahead_valid_terminator(pos: int, content: str) -> bool:
            """Look ahead: check if this quote is a valid JSON terminator"""
            j = pos + 1
            while j < len(content) and content[j] in ' \t\n\r':
                j += 1
            if j >= len(content):
                return False
            return content[j] in ',}'

        # State machine parsing
        i = 0
        n = len(json_content)
        current_key = []
        current_value = []
        state = 'outside'  # outside, in_key, after_colon, in_value

        while i < n:
            char = json_content[i]

            if state == 'outside':
                if char == '"':
                    state = 'in_key'
                    current_key = []
                elif char == '}':
                    break
                i += 1
                continue

            if state == 'in_key':
                if char == '"':
                    state = 'after_colon'
                else:
                    current_key.append(char)
                i += 1
                continue

            if state == 'after_colon':
                if char == '"':
                    state = 'in_value'
                    current_value = []
                i += 1
                continue

            if state == 'in_value':
                if char == '"':
                    if look_ahead_valid_terminator(i, json_content):
                        # value end
                        key = ''.join(current_key)
                        value = ''.join(current_value)
                        result[key] = value
                        current_key = []
                        current_value = []
                        state = 'outside'
                    else:
                        # Ordinary quote, continue accumulating
                        current_value.append(char)
                elif char == '\\' and i + 1 < n:
                    current_value.append(char)
                    current_value.append(json_content[i + 1])
                    i += 2
                    continue
                else:
                    current_value.append(char)
                i += 1
                continue

            i += 1

        if result:
            return result

        return None

    def extract(self, response: str) -> LLMRes:
        """Non-streaming JSON object extraction"""
        kv_pairs: List[Tuple[str, str]] = []

        data = self._try_parse_json(response)
        if data is not None and isinstance(data, dict):
            for key, value in data.items():
                # Serialize value to string (if complex type)
                if isinstance(value, (dict, list)):
                    kv_pairs.append((key, json.dumps(value, ensure_ascii=False)))
                else:
                    kv_pairs.append((key, str(value)))
        else:
            # JSON parse failed, use default_type
            kv_pairs.append((self.default_type, response))

        return LLMRes(kv_pairs=kv_pairs, content=response)

    def extract_stream(self, chunk: str) -> list[LLMResChunk]:
        """Streaming extraction

        JSON streaming needs to accumulate a complete object before outputting keys one by one.
        Returns the complete content of one key each time.
        Only switches to the next key after the current key is complete.
        """
        self._buffer += chunk

        # Try to parse complete JSON
        data = self._try_parse_json(self._buffer)
        if data is not None and isinstance(data, dict):
            keys = list(data.keys())

            # Initialize current key index
            if self._current_key_index is None:
                self._current_key_index = 0

            # If all keys have been output, return empty
            if self._current_key_index >= len(keys):
                return []

            current_key = keys[self._current_key_index]
            value = data[current_key]

            # Serialize value
            if isinstance(value, (dict, list)):
                value_str = json.dumps(value, ensure_ascii=False)
            else:
                value_str = str(value)

            # Output current key
            result = [LLMResChunk(
                kv_key=current_key,
                kv_delta=value_str,
                is_key_complete=True,  # when JSON is complete, all keys are complete
                raw_delta=chunk,
            )]

            # Switch to next key
            self._current_key_index += 1

            return result

        return []

    def flush_stream(self) -> list[LLMResChunk]:
        """Output all remaining keys when stream ends"""
        # If buffer hasn't parsed complete JSON, cannot output
        if self._current_key_index is None:
            return []

        data = self._try_parse_json(self._buffer)
        if data is not None and isinstance(data, dict):
            keys = list(data.keys())
            chunks = []

            # Output all remaining keys
            while self._current_key_index < len(keys):
                current_key = keys[self._current_key_index]
                value = data[current_key]

                # Serialize value
                if isinstance(value, (dict, list)):
                    value_str = json.dumps(value, ensure_ascii=False)
                else:
                    value_str = str(value)

                chunks.append(LLMResChunk(
                    kv_key=current_key,
                    kv_delta=value_str,
                    is_key_complete=True,
                    raw_delta='',
                ))

                self._current_key_index += 1

            return chunks

        return []

    def reset(self) -> None:
        """Reset streaming state"""
        self._buffer = ""
        self._current_key_index = None
